# Generated by Django 4.0.1 on 2022-01-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welderapp', '0005_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=200),
        ),
    ]
