# Generated by Django 4.0.1 on 2022-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welderapp', '0006_alter_career_email_alter_contact_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
